#!/bin/bash
# Copyright (c) 2013 Randy Thiemann
#
# This software is provided 'as-is', without any express or implied
# warranty. In no event will the authors be held liable for any damages
# arising from the use of this software.
#
# Permission is granted to anyone to use this software for any purpose,
# including commercial applications, and to alter it and redistribute it
# freely, subject to the following restrictions:
#
#    1. The origin of this software must not be misrepresented; you must not
#    claim that you wrote the original software. If you use this software
#    in a product, an acknowledgment in the product documentation would be
#    appreciated but is not required.
#
#    2. Altered source versions must be plainly marked as such, and must not be
#    misrepresented as being the original software.
#
#    3. This notice may not be removed or altered from any source
#    distribution.

GIT_HTTP_BACKEND="/usr/libexec/git-core/git-http-backend"
PROJECTS=$(dirname $GIT_PROJECT_ROOT)/projects.list

fake_git_response() {
    echo Status: 404 Not Found
    echo Expires: Fri, 01 Jan 1980 00:00:00 GMT
    echo Pragma: no-cache
    echo Cache-Control: no-cache, max-age=0, must-revalidate
    echo
    exit
}

if echo $REQUEST_URI | grep -q 'git-receive-pack'; then
    fake_git_response
fi

if grep -q $(echo $REQUEST_URI | sed 's:^/::;s:\.git.*$:.git:') $PROJECTS; then
    exec $GIT_HTTP_BACKEND
else
    fake_git_response
fi

