#!/bin/bash
#Copyright (c) 2013, Randy Thiemann
#All rights reserved.
#
#Redistribution and use in source and binary forms, with or without
#modification, are permitted provided that the following conditions are met:
#    * Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the following disclaimer in the
#      documentation and/or other materials provided with the distribution.
#    * Neither the name of the git-http-whitelist project nor the
#      names of its contributors may be used to endorse or promote products
#      derived from this software without specific prior written permission.
#
#THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
#ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
#WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
#DISCLAIMED. IN NO EVENT SHALL RANDY THIEMANN BE LIABLE FOR ANY
#DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
#(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
#LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
#ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
#(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
#SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


GIT_HTTP_BACKEND="/usr/libexec/git-core/git-http-backend"
PROJECTS=$(dirname $GIT_PROJECT_ROOT)/projects.list

fake_git_response() {
    echo Status: 404 Not Found
    echo Expires: Fri, 01 Jan 1980 00:00:00 GMT
    echo Pragma: no-cache
    echo Cache-Control: no-cache, max-age=0, must-revalidate
    echo
    exit
}

if echo $REQUEST_URI | grep -q 'git-receive-pack'; then
    fake_git_response
fi

if grep -q $(echo $REQUEST_URI | sed 's:^/::;s:\.git.*$:.git:') $PROJECTS; then
    exec $GIT_HTTP_BACKEND
else
    fake_git_response
fi

